### ISSUE TITLE
Still Getting Old Versions of Blueprints

### ISSUE THREAD

**Issue by Ranadiel** [factubsio/BubblePrints#11]
Ugh I hate posting this, but I've downloaded the 1.3.0i_0.binz file, and none of the blueprints look like they have changed to their 1.3.0 versions. As an example, here is a portion of MainCampaign that was modified in 1.3 to support importing data from Through the Ashes.
![image](https://user-images.githubusercontent.com/93090202/164973267-b93a54e3-8133-46d2-97ce-7c8b000abf8a.png)

Here is the same portion of data in bubbleprints.
![image](https://user-images.githubusercontent.com/93090202/164973325-ab412c45-193b-4253-ad71-e891e945cf23.png)

Perhaps the oddest discrepancy is that bubbleprints is still using the 1.2 localization since it still has the "bully" in DLC2 referred to as Vitko despite 1.3 changing his name to Bomir.
![image](https://user-images.githubusercontent.com/93090202/164973482-62688754-8c9c-4db4-9371-a30c1618c7ae.png)

![image](https://user-images.githubusercontent.com/93090202/164973464-7d789ac5-e191-4b91-bad7-bb018e750b28.png)

So yeah, either the wrong binz file was uploaded or my copy of bubbleprints is refusing to acknowledge that there has been an update despite downloading the file (and I have attempted downloading an update, deleting the current file to force a fresh download, and replacing the file with the version you linked me to in the old issue).

**Comment by factubsio** [comment]
It is very possible I screwed up!

What does bubble prints say at the top right of the main window?

**Comment by Ranadiel** [comment]
You mean the version number?
![image](https://user-images.githubusercontent.com/93090202/165084074-49a33b30-461d-4341-afe6-be95c392177d.png)

**Comment by factubsio** [comment]
![image](https://user-images.githubusercontent.com/65080026/165133899-d7e56c8f-f517-465c-b8e0-728ae61797d0.png)


I am a total idiot 😆 

Fixing

**Comment by factubsio** [comment]
Should be fixed now, let me know of any issues!!!

**Comment by Ranadiel** [comment]
Looks good. I'll let you know if anything else pops up. Thanks for the prompt help!
