### ISSUE TITLE
Return of the Old Versions Bug

### ISSUE THREAD

**Issue by Ranadiel** [factubsio/BubblePrints#12]
I was looking through some blueprints earlier today, and I found that the versions in Bubbleprints was out of date. Comparing blueprints to patch notes, it looks like the version that I have in Bubbleprints is 1.3.2c? I assume this is a silly typo in generating the binz file again. No idea how long the bug has been around.

Currently using version 0.25.0. 

Current binz file loaded:
![image](https://user-images.githubusercontent.com/93090202/180851260-764c4cfd-3389-4a5c-b5ec-923594837762.png)

Example of an outdated blueprint, Guid fd2e11ebb8a14d6599450fc27f03486a had a new import etude (InevitableDarkness_KilledOnUnfair) added for DLC1 in 1.3.6d. Said etude is not in the viewable files and is missing from the imported etudes:

![image](https://user-images.githubusercontent.com/93090202/180851601-5602a82d-b8cd-438b-bdcf-03372786010d.png)

I don't have any particular reason I need this fixed in a hurry, but it would be nice to have it fixed before the binz file for 1.4 (and especially before the binz file for EE) is generated. Thanks!

**Comment by factubsio** [comment]
Hmm. Possibly broke something by accident, pushed 1.4.0 can you check it is actually right? :-(

**Comment by Ranadiel** [comment]
Checking the files, MainCampaign is still a pre-1.3.6d version as it is missing the InevitableDarkness_KilledOnUnfair import. Checked for some new files that were added in 1.4 and could not find them. So yeah, the problem still appears to be there on my end.

**Comment by factubsio** [comment]
Ah fuck, I'll have a look to see what I've messed up.

Cheers for letting me know

**Comment by factubsio** [comment]
I'm an idiot and was pointing it at my dev version not the steam one :-(

**Comment by factubsio** [comment]
Should be fixed now, please let me know.

**Comment by Ranadiel** [comment]
Ah no worries. The new binz has the updated version of the MainCampaign file. Checking some additional files, it looks like the files include bugfixes from 1.4, so it appears to be fully up to date.

Thanks for the work!

**Comment by factubsio** [comment]
No worries I literally just had a hard coded path to the wrong wrath install 😔

**Comment by factubsio** [comment]
PS: I usually respond a lot quicker on discord (the wrath one in mod-dev-technical or mod-user-general) just cos github notifications absolutely suck.
