### ISSUE TITLE
No search bar in 0.22.0 or 0.22.1

### ISSUE THREAD

**Issue by Ranadiel** [factubsio/BubblePrints#9]
Updated to the most recent version yesterday, and I wasn't able to use it because I don't see a search bar and I don't see any option to enable it. Testing old versions, it looks like the problem arose in in 0.22.0 as 0.21.5 is working fine.

I'm on Windows 10 Home (64 bits). Not sure what else would be helpful for debugging. Here is a screenshot of what I am seeing in 0.22.1.

![image](https://user-images.githubusercontent.com/93090202/160221954-0a05317e-8221-4d71-aec6-817d88bf472a.png)

Here is what I am seeing in 0.21.5

![image](https://user-images.githubusercontent.com/93090202/160222109-ecae6c89-35d4-471b-b180-a937c6727900.png)

**Comment by factubsio** [comment]
0.22.x is an experimental version with `ctrl-p` (or `ctrl-f`) to show the search pane.

**Comment by Ranadiel** [comment]
Thank you for the information, and I appreciate that the new builds have this info added. Issue is resolved, so I will be closing this now.

**Comment by factubsio** [comment]
No worries, please let me know if there are issues with it or ways you think it could be better!
